name: Publish unstable builds

on: push

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra:  ["10.3.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@b53614dada0a16e3c342277caae905b96d803109
        with:
          version: ${{ matrix.ghidra }}
      - name: Download stdump
        run: bash ./os/download.sh
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: test -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - name: Build Extension
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}
      - name: Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*ghidra-emotionengine-reloaded.zip
          tag: "unstable"
          overwrite: true
          file_glob: true
